# Generated by Django 6.0 on 2026-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='temur/')),
                ('status', models.CharField(choices=[('Собран на складе', 'Собран на складе'), ('Отправлен', 'Отправлен'), ('Получен', 'Получен')], default='Собран на складе', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customers', models.ManyToManyField(to='temur.customername')),
            ],
        ),
    ]
