# Generated by Django 6.0 on 2026-01-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_car', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('number_engine', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NummerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(default='0 KG ', max_length=100)),
                ('chance_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='temur.car')),
            ],
        ),
    ]
