# Generated by Django 6.0 on 2026-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_todo', models.CharField(max_length=100, verbose_name='enter your todo')),
                ('plans', models.TextField(blank=True, verbose_name='enter your_plan')),
                ('status', models.CharField(choices=[('✅', '✅'), ('❌', '❌')], default='❌', max_length=100, verbose_name='enter your status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tasks',
                'verbose_name_plural': 'task',
            },
        ),
    ]
