# Generated by Django 6.0 on 2025-12-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('description', models.TextField()),
                ('type_blog', models.CharField(choices=[('Education', 'Education'), ('Travel', 'Travel')], default='Education', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
