# Generated by Django 6.0 on 2026-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options_alter_reviews_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name_blog',
            field=models.CharField(max_length=100, verbose_name='enter your name blog'),
        ),
    ]
